/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GamePad: typeof import('./src/components/GamePad.vue')['default']
    GamePadComponent: typeof import('./src/components/GamePadComponent.vue')['default']
    GamePadSvg: typeof import('./src/components/GamePadSvg.vue')['default']
    HangarSky: typeof import('./src/components/HangarSky.vue')['default']
    Mobilejoystick: typeof import('./src/components/Mobilejoystick.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
